// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: module/peggy/v1beta1/attestation.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClaimType is the cosmos type of an event from the counterpart chain that can be handled
type ClaimType int32

const (
	CLAIM_TYPE_UNKNOWN                          ClaimType = 0
	CLAIM_TYPE_ETHEREUM_BRIDGE_DEPOSIT          ClaimType = 1
	CLAIM_TYPE_ETHEREUM_BRIDGE_WITHDRAWAL_BATCH ClaimType = 2
)

var ClaimType_name = map[int32]string{
	0: "CLAIM_TYPE_UNKNOWN",
	1: "CLAIM_TYPE_ETHEREUM_BRIDGE_DEPOSIT",
	2: "CLAIM_TYPE_ETHEREUM_BRIDGE_WITHDRAWAL_BATCH",
}

var ClaimType_value = map[string]int32{
	"CLAIM_TYPE_UNKNOWN":                          0,
	"CLAIM_TYPE_ETHEREUM_BRIDGE_DEPOSIT":          1,
	"CLAIM_TYPE_ETHEREUM_BRIDGE_WITHDRAWAL_BATCH": 2,
}

func (x ClaimType) String() string {
	return proto.EnumName(ClaimType_name, int32(x))
}

func (ClaimType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_944d06a2eda238c5, []int{0}
}

// Attestation is an aggregate of `claims` that eventually becomes `observed` by all orchestrators
type Attestation struct {
	ClaimType  ClaimType  `protobuf:"varint,1,opt,name=claim_type,json=claimType,proto3,enum=module.peggy.v1beta1.ClaimType" json:"claim_type,omitempty"`
	EventNonce uint64     `protobuf:"varint,2,opt,name=event_nonce,json=eventNonce,proto3" json:"event_nonce,omitempty"`
	Observed   bool       `protobuf:"varint,3,opt,name=observed,proto3" json:"observed,omitempty"`
	Votes      []string   `protobuf:"bytes,4,rep,name=votes,proto3" json:"votes,omitempty"`
	Details    *types.Any `protobuf:"bytes,5,opt,name=details,proto3" json:"details,omitempty"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_944d06a2eda238c5, []int{0}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return m.Size()
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetClaimType() ClaimType {
	if m != nil {
		return m.ClaimType
	}
	return CLAIM_TYPE_UNKNOWN
}

func (m *Attestation) GetEventNonce() uint64 {
	if m != nil {
		return m.EventNonce
	}
	return 0
}

func (m *Attestation) GetObserved() bool {
	if m != nil {
		return m.Observed
	}
	return false
}

func (m *Attestation) GetVotes() []string {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Attestation) GetDetails() *types.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

// WithdrawalBatch is an attestation detail that marks a batch of outgoing transactions executed and
// frees earlier unexecuted batches
type WithdrawalBatch struct {
	BatchNonce  int64       `protobuf:"varint,1,opt,name=batch_nonce,json=batchNonce,proto3" json:"batch_nonce,omitempty"`
	Erc_20Token *ERC20Token `protobuf:"bytes,2,opt,name=erc_20_token,json=erc20Token,proto3" json:"erc_20_token,omitempty"`
}

func (m *WithdrawalBatch) Reset()         { *m = WithdrawalBatch{} }
func (m *WithdrawalBatch) String() string { return proto.CompactTextString(m) }
func (*WithdrawalBatch) ProtoMessage()    {}
func (*WithdrawalBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_944d06a2eda238c5, []int{1}
}
func (m *WithdrawalBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawalBatch.Unmarshal(m, b)
}
func (m *WithdrawalBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawalBatch.Marshal(b, m, deterministic)
}
func (m *WithdrawalBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawalBatch.Merge(m, src)
}
func (m *WithdrawalBatch) XXX_Size() int {
	return xxx_messageInfo_WithdrawalBatch.Size(m)
}
func (m *WithdrawalBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawalBatch.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawalBatch proto.InternalMessageInfo

func (m *WithdrawalBatch) GetBatchNonce() int64 {
	if m != nil {
		return m.BatchNonce
	}
	return 0
}

func (m *WithdrawalBatch) GetErc_20Token() *ERC20Token {
	if m != nil {
		return m.Erc_20Token
	}
	return nil
}

// // BridgeDeposit is an attestation detail that adds vouchers to an account when executed
type BridgeDeposit struct {
	Erc_20Token    *ERC20Token `protobuf:"bytes,1,opt,name=erc_20_token,json=erc20Token,proto3" json:"erc_20_token,omitempty"`
	EthereumSender []byte      `protobuf:"bytes,2,opt,name=ethereum_sender,json=ethereumSender,proto3" json:"ethereum_sender,omitempty"`
	CosmosReceiver string      `protobuf:"bytes,3,opt,name=cosmos_receiver,json=cosmosReceiver,proto3" json:"cosmos_receiver,omitempty"`
}

func (m *BridgeDeposit) Reset()         { *m = BridgeDeposit{} }
func (m *BridgeDeposit) String() string { return proto.CompactTextString(m) }
func (*BridgeDeposit) ProtoMessage()    {}
func (*BridgeDeposit) Descriptor() ([]byte, []int) {
	return fileDescriptor_944d06a2eda238c5, []int{2}
}
func (m *BridgeDeposit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BridgeDeposit.Unmarshal(m, b)
}
func (m *BridgeDeposit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BridgeDeposit.Marshal(b, m, deterministic)
}
func (m *BridgeDeposit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeDeposit.Merge(m, src)
}
func (m *BridgeDeposit) XXX_Size() int {
	return xxx_messageInfo_BridgeDeposit.Size(m)
}
func (m *BridgeDeposit) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeDeposit.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeDeposit proto.InternalMessageInfo

func (m *BridgeDeposit) GetErc_20Token() *ERC20Token {
	if m != nil {
		return m.Erc_20Token
	}
	return nil
}

func (m *BridgeDeposit) GetEthereumSender() []byte {
	if m != nil {
		return m.EthereumSender
	}
	return nil
}

func (m *BridgeDeposit) GetCosmosReceiver() string {
	if m != nil {
		return m.CosmosReceiver
	}
	return ""
}

// ERC20Token unique identifier for an Ethereum erc20 token.
type ERC20Token struct {
	// option (gogoproto.sizer)      = false;
	// NOTE: i've migrated this to use sdk.Int as per the discussion earlier
	// TODO: fix the sdk.Int generated code here
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	// uint64 amount                 = 1;
	Symbol               string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	TokenContractAddress []byte `protobuf:"bytes,3,opt,name=token_contract_address,json=tokenContractAddress,proto3" json:"token_contract_address,omitempty"`
}

func (m *ERC20Token) Reset()         { *m = ERC20Token{} }
func (m *ERC20Token) String() string { return proto.CompactTextString(m) }
func (*ERC20Token) ProtoMessage()    {}
func (*ERC20Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_944d06a2eda238c5, []int{3}
}
func (m *ERC20Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ERC20Token.Unmarshal(m, b)
}
func (m *ERC20Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ERC20Token.Marshal(b, m, deterministic)
}
func (m *ERC20Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ERC20Token.Merge(m, src)
}
func (m *ERC20Token) XXX_Size() int {
	return xxx_messageInfo_ERC20Token.Size(m)
}
func (m *ERC20Token) XXX_DiscardUnknown() {
	xxx_messageInfo_ERC20Token.DiscardUnknown(m)
}

var xxx_messageInfo_ERC20Token proto.InternalMessageInfo

func (m *ERC20Token) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ERC20Token) GetTokenContractAddress() []byte {
	if m != nil {
		return m.TokenContractAddress
	}
	return nil
}

func init() {
	proto.RegisterEnum("module.peggy.v1beta1.ClaimType", ClaimType_name, ClaimType_value)
	proto.RegisterType((*Attestation)(nil), "module.peggy.v1beta1.Attestation")
	proto.RegisterType((*WithdrawalBatch)(nil), "module.peggy.v1beta1.WithdrawalBatch")
	proto.RegisterType((*BridgeDeposit)(nil), "module.peggy.v1beta1.BridgeDeposit")
	proto.RegisterType((*ERC20Token)(nil), "module.peggy.v1beta1.ERC20Token")
}

func init() {
	proto.RegisterFile("module/peggy/v1beta1/attestation.proto", fileDescriptor_944d06a2eda238c5)
}

var fileDescriptor_944d06a2eda238c5 = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x4e, 0xdb, 0x4a,
	0x14, 0xf6, 0xf0, 0x77, 0xc9, 0x24, 0x17, 0xd0, 0x28, 0x8a, 0x72, 0xb3, 0x48, 0xac, 0x2c, 0xb8,
	0xd1, 0xbd, 0xc2, 0x81, 0xb4, 0xab, 0x2e, 0x2a, 0xc5, 0x49, 0x28, 0x69, 0x21, 0xa0, 0x21, 0x28,
	0x6a, 0x37, 0xee, 0xc4, 0x3e, 0x75, 0x2c, 0x62, 0x4f, 0x64, 0x4f, 0xd2, 0x66, 0xdf, 0x05, 0x62,
	0xc5, 0x0b, 0x20, 0x15, 0xf5, 0x05, 0x2a, 0xb5, 0x0f, 0x81, 0xba, 0x62, 0x59, 0x75, 0x81, 0x2a,
	0xd8, 0x74, 0xdf, 0x17, 0xa8, 0x3c, 0x76, 0x80, 0xb6, 0xa8, 0x2a, 0xab, 0x9c, 0xf3, 0x7d, 0xdf,
	0xc9, 0xf9, 0xce, 0xcc, 0xf1, 0xe0, 0x65, 0x97, 0x5b, 0xc3, 0x3e, 0x94, 0x07, 0x60, 0xdb, 0xe3,
	0xf2, 0x68, 0xad, 0x0b, 0x82, 0xad, 0x95, 0x99, 0x10, 0x10, 0x08, 0x26, 0x1c, 0xee, 0x69, 0x03,
	0x9f, 0x0b, 0x4e, 0xd2, 0x91, 0x4e, 0x93, 0x3a, 0x2d, 0xd6, 0xe5, 0xd2, 0x36, 0xb7, 0xb9, 0x14,
	0x94, 0xc3, 0x28, 0xd2, 0xe6, 0xfe, 0xb1, 0x39, 0xb7, 0xc3, 0xff, 0x0c, 0xb3, 0xee, 0xf0, 0x45,
	0x99, 0x79, 0xe3, 0x09, 0x65, 0xf2, 0xc0, 0xe5, 0x81, 0x11, 0xd5, 0x44, 0x49, 0x44, 0x15, 0xbf,
	0x22, 0x9c, 0xac, 0x5e, 0xf7, 0x25, 0x0f, 0x31, 0x36, 0xfb, 0xcc, 0x71, 0x0d, 0x31, 0x1e, 0x40,
	0x16, 0xa9, 0xa8, 0xb4, 0x50, 0x29, 0x68, 0xb7, 0xd9, 0xd0, 0x6a, 0xa1, 0xae, 0x3d, 0x1e, 0x00,
	0x4d, 0x98, 0x93, 0x90, 0x14, 0x70, 0x12, 0x46, 0xe0, 0x09, 0xc3, 0xe3, 0x9e, 0x09, 0xd9, 0x29,
	0x15, 0x95, 0x66, 0x28, 0x96, 0x50, 0x2b, 0x44, 0x48, 0x0e, 0xcf, 0xf3, 0x6e, 0x00, 0xfe, 0x08,
	0xac, 0xec, 0xb4, 0x8a, 0x4a, 0xf3, 0xf4, 0x2a, 0x27, 0x69, 0x3c, 0x3b, 0xe2, 0x02, 0x82, 0xec,
	0x8c, 0x3a, 0x5d, 0x4a, 0xd0, 0x28, 0x21, 0xeb, 0xf8, 0x2f, 0x0b, 0x04, 0x73, 0xfa, 0x41, 0x76,
	0x56, 0x45, 0xa5, 0x64, 0x25, 0xad, 0x45, 0xa3, 0x6a, 0x93, 0x51, 0xb5, 0xaa, 0x37, 0xd6, 0x33,
	0x1f, 0x3f, 0xac, 0x90, 0x1b, 0xa3, 0xd4, 0xa3, 0x1a, 0x3a, 0x29, 0x2e, 0xbe, 0x46, 0x78, 0xb1,
	0xe3, 0x88, 0x9e, 0xe5, 0xb3, 0x97, 0xac, 0xaf, 0x33, 0x61, 0xf6, 0x42, 0xbb, 0xdd, 0x30, 0x88,
	0xed, 0x86, 0xf3, 0x4e, 0x53, 0x2c, 0xa1, 0xc8, 0xae, 0x8e, 0x53, 0xe0, 0x9b, 0x46, 0x65, 0xd5,
	0x10, 0x7c, 0x1f, 0x3c, 0x39, 0x50, 0xb2, 0xa2, 0xde, 0x7e, 0x22, 0x0d, 0x5a, 0xab, 0xac, 0xb6,
	0x43, 0x1d, 0xc5, 0xe0, 0x9b, 0x71, 0xfc, 0x20, 0x75, 0x70, 0x52, 0x50, 0x8e, 0x4e, 0x0a, 0xca,
	0x9b, 0x93, 0x82, 0x52, 0x7c, 0x8f, 0xf0, 0xdf, 0xba, 0xef, 0x58, 0x36, 0xd4, 0x61, 0xc0, 0x03,
	0x47, 0xfc, 0xd2, 0x03, 0xdd, 0xbd, 0x07, 0xf9, 0x17, 0x2f, 0x82, 0xe8, 0x81, 0x0f, 0x43, 0xd7,
	0x08, 0xc0, 0xb3, 0xc0, 0x97, 0x56, 0x53, 0x74, 0x61, 0x02, 0xef, 0x4a, 0x34, 0x14, 0xc6, 0xdb,
	0xe0, 0x83, 0x09, 0xce, 0x08, 0x7c, 0x79, 0x0d, 0x09, 0xba, 0x10, 0xc1, 0x34, 0x46, 0x7f, 0x72,
	0xfd, 0x0e, 0x61, 0x7c, 0xdd, 0x9a, 0xac, 0xe3, 0x39, 0xe6, 0xf2, 0xa1, 0x27, 0xa4, 0xd9, 0x84,
	0xae, 0x9d, 0x9e, 0x17, 0x94, 0xcf, 0xe7, 0x85, 0x65, 0xdb, 0x11, 0xbd, 0x61, 0x57, 0x33, 0xb9,
	0x1b, 0xef, 0x59, 0xfc, 0xb3, 0x12, 0x58, 0xfb, 0xe5, 0x70, 0xa7, 0x02, 0xad, 0xe9, 0x09, 0x1a,
	0x57, 0x93, 0x0c, 0x9e, 0x0b, 0xc6, 0x6e, 0x97, 0xf7, 0xa5, 0xdb, 0x04, 0x8d, 0x33, 0x72, 0x1f,
	0x67, 0xe4, 0x59, 0x18, 0x26, 0xf7, 0x84, 0xcf, 0x4c, 0x61, 0x30, 0xcb, 0xf2, 0x21, 0x08, 0xa4,
	0xd9, 0x14, 0x4d, 0x4b, 0xb6, 0x16, 0x93, 0xd5, 0x88, 0xfb, 0xd1, 0xf2, 0x7f, 0xdf, 0x10, 0x4e,
	0x5c, 0xed, 0x28, 0xd1, 0x30, 0xa9, 0x6d, 0x56, 0x9b, 0x5b, 0x46, 0xfb, 0xe9, 0x4e, 0xc3, 0xd8,
	0x6b, 0x3d, 0x69, 0x6d, 0x77, 0x5a, 0x4b, 0x4a, 0x2e, 0x73, 0x78, 0xac, 0xde, 0xc2, 0x90, 0x16,
	0x2e, 0xde, 0x40, 0x1b, 0xed, 0x8d, 0x06, 0x6d, 0xec, 0x6d, 0x19, 0x3a, 0x6d, 0xd6, 0x1f, 0x35,
	0x8c, 0x7a, 0x63, 0x67, 0x7b, 0xb7, 0xd9, 0x5e, 0x42, 0xb9, 0xe5, 0xc3, 0x63, 0xf5, 0x0f, 0x94,
	0xe4, 0x39, 0xfe, 0xff, 0x37, 0xaa, 0x4e, 0xb3, 0xbd, 0x51, 0xa7, 0xd5, 0x4e, 0x75, 0xd3, 0xd0,
	0xab, 0xed, 0xda, 0xc6, 0xd2, 0x54, 0xae, 0x7c, 0x78, 0xac, 0xde, 0xa5, 0x24, 0x37, 0x73, 0xf0,
	0x36, 0xaf, 0xe8, 0x8f, 0x4f, 0x2f, 0xf2, 0xe8, 0xec, 0x22, 0x8f, 0xbe, 0x5c, 0xe4, 0xd1, 0xd1,
	0x65, 0x5e, 0x39, 0xbb, 0xcc, 0x2b, 0x9f, 0x2e, 0xf3, 0xca, 0xb3, 0xd5, 0x1b, 0x77, 0xc3, 0xfa,
	0xa2, 0x07, 0x6c, 0xc5, 0x03, 0x11, 0xbf, 0x41, 0xf1, 0x83, 0xf4, 0x2a, 0x4e, 0xe5, 0x4d, 0x75,
	0xe7, 0xe4, 0x07, 0x76, 0xef, 0x7b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xf4, 0xba, 0x91, 0xaf,
	0x04, 0x00, 0x00,
}

func (m *Attestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Details != nil {
		{
			size, err := m.Details.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAttestation(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Votes[iNdEx])
			copy(dAtA[i:], m.Votes[iNdEx])
			i = encodeVarintAttestation(dAtA, i, uint64(len(m.Votes[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Observed {
		i--
		if m.Observed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.EventNonce != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.EventNonce))
		i--
		dAtA[i] = 0x10
	}
	if m.ClaimType != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.ClaimType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAttestation(dAtA []byte, offset int, v uint64) int {
	offset -= sovAttestation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Attestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClaimType != 0 {
		n += 1 + sovAttestation(uint64(m.ClaimType))
	}
	if m.EventNonce != 0 {
		n += 1 + sovAttestation(uint64(m.EventNonce))
	}
	if m.Observed {
		n += 2
	}
	if len(m.Votes) > 0 {
		for _, s := range m.Votes {
			l = len(s)
			n += 1 + l + sovAttestation(uint64(l))
		}
	}
	if m.Details != nil {
		l = m.Details.Size()
		n += 1 + l + sovAttestation(uint64(l))
	}
	return n
}

func sovAttestation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAttestation(x uint64) (n int) {
	return sovAttestation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Attestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimType", wireType)
			}
			m.ClaimType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ClaimType |= ClaimType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EventNonce", wireType)
			}
			m.EventNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EventNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Observed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Observed = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Details", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Details == nil {
				m.Details = &types.Any{}
			}
			if err := m.Details.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAttestation
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAttestation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAttestation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAttestation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAttestation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAttestation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAttestation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttestation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttestation = fmt.Errorf("proto: unexpected end of group")
)
