// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: module/peggy/v1beta1/batch.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BatchStatus int32

const (
	OptionEmpty            BatchStatus = 0
	BATCH_STATUS_PENDING   BatchStatus = 1
	BATCH_STATUS_SUBMITTED BatchStatus = 2
	BATCH_STATUS_PROCESSED BatchStatus = 3
	BATCH_STATUS_CANCELED  BatchStatus = 4
)

var BatchStatus_name = map[int32]string{
	0: "BATCH_STATUS_UNKNOWN",
	1: "BATCH_STATUS_PENDING",
	2: "BATCH_STATUS_SUBMITTED",
	3: "BATCH_STATUS_PROCESSED",
	4: "BATCH_STATUS_CANCELED",
}

var BatchStatus_value = map[string]int32{
	"BATCH_STATUS_UNKNOWN":   0,
	"BATCH_STATUS_PENDING":   1,
	"BATCH_STATUS_SUBMITTED": 2,
	"BATCH_STATUS_PROCESSED": 3,
	"BATCH_STATUS_CANCELED":  4,
}

func (x BatchStatus) String() string {
	return proto.EnumName(BatchStatus_name, int32(x))
}

func (BatchStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9735c82168ab3388, []int{0}
}

type OutgoingTxBatch struct {
	Nonce              uint64                `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Elements           []*OutgoingTransferTx `protobuf:"bytes,2,rep,name=elements,proto3" json:"elements,omitempty"`
	CreatedAt          time.Time             `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at"`
	TotalFee           *ERC20Token           `protobuf:"bytes,4,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	BridgedDenominator *BridgedDenominator   `protobuf:"bytes,5,opt,name=bridged_denominator,json=bridgedDenominator,proto3" json:"bridged_denominator,omitempty"`
	BatchStatus        BatchStatus           `protobuf:"varint,6,opt,name=batch_status,json=batchStatus,proto3,enum=module.peggy.v1beta1.BatchStatus" json:"batch_status,omitempty"`
	Valset             *Valset               `protobuf:"bytes,7,opt,name=valset,proto3" json:"valset,omitempty"`
	TokenContract      []byte                `protobuf:"bytes,8,opt,name=token_contract,json=tokenContract,proto3" json:"token_contract,omitempty"`
}

func (m *OutgoingTxBatch) Reset()         { *m = OutgoingTxBatch{} }
func (m *OutgoingTxBatch) String() string { return proto.CompactTextString(m) }
func (*OutgoingTxBatch) ProtoMessage()    {}
func (*OutgoingTxBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_9735c82168ab3388, []int{0}
}
func (m *OutgoingTxBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutgoingTxBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OutgoingTxBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OutgoingTxBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutgoingTxBatch.Merge(m, src)
}
func (m *OutgoingTxBatch) XXX_Size() int {
	return m.Size()
}
func (m *OutgoingTxBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_OutgoingTxBatch.DiscardUnknown(m)
}

var xxx_messageInfo_OutgoingTxBatch proto.InternalMessageInfo

func (m *OutgoingTxBatch) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *OutgoingTxBatch) GetElements() []*OutgoingTransferTx {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *OutgoingTxBatch) GetCreatedAt() time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return time.Time{}
}

func (m *OutgoingTxBatch) GetTotalFee() *ERC20Token {
	if m != nil {
		return m.TotalFee
	}
	return nil
}

func (m *OutgoingTxBatch) GetBridgedDenominator() *BridgedDenominator {
	if m != nil {
		return m.BridgedDenominator
	}
	return nil
}

func (m *OutgoingTxBatch) GetBatchStatus() BatchStatus {
	if m != nil {
		return m.BatchStatus
	}
	return OptionEmpty
}

func (m *OutgoingTxBatch) GetValset() *Valset {
	if m != nil {
		return m.Valset
	}
	return nil
}

func (m *OutgoingTxBatch) GetTokenContract() []byte {
	if m != nil {
		return m.TokenContract
	}
	return nil
}

type OutgoingTransferTx struct {
	Id          uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sender      string      `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	DestAddress []byte      `protobuf:"bytes,3,opt,name=dest_address,json=destAddress,proto3" json:"dest_address,omitempty"`
	Amount      *ERC20Token `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	BridgeFee   *ERC20Token `protobuf:"bytes,5,opt,name=bridge_fee,json=bridgeFee,proto3" json:"bridge_fee,omitempty"`
}

func (m *OutgoingTransferTx) Reset()         { *m = OutgoingTransferTx{} }
func (m *OutgoingTransferTx) String() string { return proto.CompactTextString(m) }
func (*OutgoingTransferTx) ProtoMessage()    {}
func (*OutgoingTransferTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_9735c82168ab3388, []int{1}
}
func (m *OutgoingTransferTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OutgoingTransferTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OutgoingTransferTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OutgoingTransferTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutgoingTransferTx.Merge(m, src)
}
func (m *OutgoingTransferTx) XXX_Size() int {
	return m.Size()
}
func (m *OutgoingTransferTx) XXX_DiscardUnknown() {
	xxx_messageInfo_OutgoingTransferTx.DiscardUnknown(m)
}

var xxx_messageInfo_OutgoingTransferTx proto.InternalMessageInfo

func (m *OutgoingTransferTx) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OutgoingTransferTx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *OutgoingTransferTx) GetDestAddress() []byte {
	if m != nil {
		return m.DestAddress
	}
	return nil
}

func (m *OutgoingTransferTx) GetAmount() *ERC20Token {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *OutgoingTransferTx) GetBridgeFee() *ERC20Token {
	if m != nil {
		return m.BridgeFee
	}
	return nil
}

func init() {
	proto.RegisterEnum("module.peggy.v1beta1.BatchStatus", BatchStatus_name, BatchStatus_value)
	proto.RegisterType((*OutgoingTxBatch)(nil), "module.peggy.v1beta1.OutgoingTxBatch")
	proto.RegisterType((*OutgoingTransferTx)(nil), "module.peggy.v1beta1.OutgoingTransferTx")
}

func init() { proto.RegisterFile("module/peggy/v1beta1/batch.proto", fileDescriptor_9735c82168ab3388) }

var fileDescriptor_9735c82168ab3388 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0x6e, 0xd3, 0x4c,
	0x14, 0xc5, 0xe3, 0x24, 0xcd, 0x97, 0x4c, 0xf2, 0xb5, 0xd1, 0x10, 0x2a, 0x13, 0x21, 0xd7, 0xad,
	0x04, 0x32, 0x48, 0x38, 0x6d, 0x60, 0xc1, 0x06, 0xa1, 0xc4, 0x76, 0xa1, 0xfc, 0x49, 0x2a, 0xc7,
	0x05, 0xc1, 0xc6, 0x1a, 0xc7, 0xb7, 0xae, 0x45, 0xec, 0xb1, 0xec, 0x49, 0xd5, 0xbe, 0x01, 0x62,
	0xd5, 0x17, 0x60, 0xc5, 0x92, 0x17, 0xe9, 0xb2, 0x4b, 0xc4, 0x02, 0x50, 0xfb, 0x00, 0xbc, 0x02,
	0xf2, 0xd8, 0x6d, 0x29, 0x4d, 0xa5, 0xee, 0x7c, 0xef, 0xfc, 0xce, 0xd5, 0x9c, 0x39, 0xbe, 0x48,
	0x0e, 0xa8, 0x3b, 0x9d, 0x40, 0x27, 0x02, 0xcf, 0xdb, 0xef, 0xec, 0xae, 0x39, 0xc0, 0xc8, 0x5a,
	0xc7, 0x21, 0x6c, 0xbc, 0xa3, 0x46, 0x31, 0x65, 0x14, 0xb7, 0x32, 0x42, 0xe5, 0x84, 0x9a, 0x13,
	0xed, 0x96, 0x47, 0x3d, 0xca, 0x81, 0x4e, 0xfa, 0x95, 0xb1, 0xed, 0xbb, 0x33, 0xa7, 0x11, 0xc6,
	0x20, 0x61, 0x84, 0xf9, 0x34, 0xcc, 0xb9, 0x25, 0x8f, 0x52, 0x2f, 0xe5, 0xd2, 0xca, 0x99, 0x6e,
	0x77, 0x98, 0x1f, 0xa4, 0x48, 0x10, 0x9d, 0x02, 0x33, 0x07, 0x45, 0x94, 0x4e, 0x72, 0x60, 0xf6,
	0xbd, 0xd9, 0x7e, 0x04, 0x49, 0x46, 0xac, 0xfc, 0x2e, 0xa1, 0x85, 0xe1, 0x94, 0x79, 0xd4, 0x0f,
	0x3d, 0x6b, 0xaf, 0x9f, 0x3a, 0xc2, 0x2d, 0x34, 0x17, 0xd2, 0x70, 0x0c, 0xa2, 0x20, 0x0b, 0x4a,
	0xd9, 0xcc, 0x0a, 0xac, 0xa3, 0x2a, 0x4c, 0x20, 0x80, 0x90, 0x25, 0x62, 0x51, 0x2e, 0x29, 0xf5,
	0xae, 0xa2, 0xce, 0x32, 0xad, 0x9e, 0x8d, 0x8b, 0x49, 0x98, 0x6c, 0x43, 0x6c, 0xed, 0x99, 0x67,
	0x4a, 0xac, 0x21, 0x34, 0x8e, 0x81, 0x30, 0x70, 0x6d, 0xc2, 0xc4, 0x92, 0x2c, 0x28, 0xf5, 0x6e,
	0x5b, 0xcd, 0x8c, 0xaa, 0xa7, 0x46, 0x55, 0xeb, 0xd4, 0x68, 0xbf, 0x7a, 0xf8, 0x63, 0xa9, 0x70,
	0xf0, 0x73, 0x49, 0x30, 0x6b, 0xb9, 0xae, 0xc7, 0xf0, 0x13, 0x54, 0x63, 0x94, 0x91, 0x89, 0xbd,
	0x0d, 0x20, 0x96, 0xf9, 0x0c, 0x79, 0xf6, 0x5d, 0x0c, 0x53, 0xeb, 0xae, 0x5a, 0xf4, 0x03, 0x84,
	0x66, 0x95, 0x4b, 0xd6, 0x01, 0xf0, 0x3b, 0x74, 0xc3, 0x89, 0x7d, 0xd7, 0x03, 0xd7, 0x76, 0x21,
	0xa4, 0x81, 0x1f, 0x12, 0x46, 0x63, 0x71, 0x8e, 0x0f, 0xba, 0xc2, 0x54, 0x3f, 0x13, 0xe8, 0xe7,
	0xbc, 0x89, 0x9d, 0x4b, 0x3d, 0xac, 0xa3, 0x06, 0xff, 0x2b, 0xec, 0x34, 0xc9, 0x69, 0x22, 0x56,
	0x64, 0x41, 0x99, 0xef, 0x2e, 0x5f, 0x31, 0x33, 0x25, 0x47, 0x1c, 0x34, 0xeb, 0xce, 0x79, 0x81,
	0x1f, 0xa1, 0xca, 0x2e, 0x99, 0x24, 0xc0, 0xc4, 0xff, 0xf8, 0x9d, 0x6e, 0xcf, 0xd6, 0xbf, 0xe1,
	0x8c, 0x99, 0xb3, 0xf8, 0x0e, 0x9a, 0x67, 0xa9, 0x53, 0x7b, 0x4c, 0x43, 0x16, 0x93, 0x31, 0x13,
	0xab, 0xb2, 0xa0, 0x34, 0xcc, 0xff, 0x79, 0x57, 0xcb, 0x9b, 0x2b, 0xdf, 0x05, 0x84, 0x2f, 0x47,
	0x84, 0xe7, 0x51, 0xd1, 0x77, 0xf3, 0xc4, 0x8b, 0xbe, 0x8b, 0x17, 0x51, 0x25, 0x81, 0xd0, 0x85,
	0x58, 0x2c, 0xca, 0x82, 0x52, 0x33, 0xf3, 0x0a, 0x2f, 0xa3, 0x86, 0x0b, 0x09, 0xb3, 0x89, 0xeb,
	0xc6, 0x90, 0x24, 0x3c, 0xc2, 0x86, 0x59, 0x4f, 0x7b, 0xbd, 0xac, 0x85, 0x1f, 0xa3, 0x0a, 0x09,
	0xe8, 0x34, 0x64, 0xd7, 0xce, 0x26, 0xe7, 0xf1, 0x53, 0x84, 0xb2, 0x47, 0xe5, 0xc9, 0xce, 0x5d,
	0x53, 0x5d, 0xcb, 0x34, 0xeb, 0x00, 0xf7, 0xbf, 0x0a, 0xa8, 0xfe, 0xd7, 0xb3, 0xe2, 0x7b, 0xa8,
	0xd5, 0xef, 0x59, 0xda, 0x73, 0x7b, 0x64, 0xf5, 0xac, 0xad, 0x91, 0xbd, 0x35, 0x78, 0x39, 0x18,
	0xbe, 0x1d, 0x34, 0x0b, 0xed, 0x85, 0x4f, 0x9f, 0xe5, 0xfa, 0x30, 0x4a, 0xd7, 0xcd, 0x08, 0x22,
	0xb6, 0x8f, 0xc5, 0x7f, 0xd0, 0x4d, 0x63, 0xa0, 0x6f, 0x0c, 0x9e, 0x35, 0x05, 0xdc, 0x46, 0x8b,
	0x17, 0x4e, 0x46, 0x5b, 0xfd, 0xd7, 0x1b, 0x96, 0x65, 0xe8, 0xcd, 0xe2, 0xa5, 0xb3, 0x4d, 0x73,
	0xa8, 0x19, 0xa3, 0x91, 0xa1, 0x37, 0x4b, 0xf8, 0x16, 0xba, 0x79, 0xe1, 0x4c, 0xeb, 0x0d, 0x34,
	0xe3, 0x95, 0xa1, 0x37, 0xcb, 0xed, 0xf2, 0xc7, 0x2f, 0x52, 0xa1, 0xff, 0xe2, 0xf0, 0x58, 0x12,
	0x8e, 0x8e, 0x25, 0xe1, 0xd7, 0xb1, 0x24, 0x1c, 0x9c, 0x48, 0x85, 0xa3, 0x13, 0xa9, 0xf0, 0xed,
	0x44, 0x2a, 0xbc, 0x5f, 0xf5, 0x7c, 0xb6, 0x33, 0x75, 0xd4, 0x31, 0x0d, 0x3a, 0x64, 0xc2, 0x76,
	0x80, 0x3c, 0x08, 0x81, 0xe5, 0x7b, 0x9c, 0x2f, 0xf5, 0x5e, 0x5e, 0xf2, 0x75, 0x76, 0x2a, 0x7c,
	0x79, 0x1e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x02, 0xd3, 0x90, 0xba, 0xab, 0x04, 0x00, 0x00,
}

func (m *OutgoingTxBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutgoingTxBatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutgoingTxBatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TokenContract) > 0 {
		i -= len(m.TokenContract)
		copy(dAtA[i:], m.TokenContract)
		i = encodeVarintBatch(dAtA, i, uint64(len(m.TokenContract)))
		i--
		dAtA[i] = 0x42
	}
	if m.Valset != nil {
		{
			size, err := m.Valset.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.BatchStatus != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.BatchStatus))
		i--
		dAtA[i] = 0x30
	}
	if m.BridgedDenominator != nil {
		{
			size, err := m.BridgedDenominator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.TotalFee != nil {
		{
			size, err := m.TotalFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintBatch(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x1a
	if len(m.Elements) > 0 {
		for iNdEx := len(m.Elements) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Elements[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBatch(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Nonce != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OutgoingTransferTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OutgoingTransferTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OutgoingTransferTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BridgeFee != nil {
		{
			size, err := m.BridgeFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Amount != nil {
		{
			size, err := m.Amount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintBatch(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.DestAddress) > 0 {
		i -= len(m.DestAddress)
		copy(dAtA[i:], m.DestAddress)
		i = encodeVarintBatch(dAtA, i, uint64(len(m.DestAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintBatch(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintBatch(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBatch(dAtA []byte, offset int, v uint64) int {
	offset -= sovBatch(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OutgoingTxBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Nonce != 0 {
		n += 1 + sovBatch(uint64(m.Nonce))
	}
	if len(m.Elements) > 0 {
		for _, e := range m.Elements {
			l = e.Size()
			n += 1 + l + sovBatch(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.CreatedAt)
	n += 1 + l + sovBatch(uint64(l))
	if m.TotalFee != nil {
		l = m.TotalFee.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	if m.BridgedDenominator != nil {
		l = m.BridgedDenominator.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	if m.BatchStatus != 0 {
		n += 1 + sovBatch(uint64(m.BatchStatus))
	}
	if m.Valset != nil {
		l = m.Valset.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	l = len(m.TokenContract)
	if l > 0 {
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}

func (m *OutgoingTransferTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBatch(uint64(m.Id))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovBatch(uint64(l))
	}
	l = len(m.DestAddress)
	if l > 0 {
		n += 1 + l + sovBatch(uint64(l))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	if m.BridgeFee != nil {
		l = m.BridgeFee.Size()
		n += 1 + l + sovBatch(uint64(l))
	}
	return n
}

func sovBatch(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBatch(x uint64) (n int) {
	return sovBatch(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OutgoingTxBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutgoingTxBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutgoingTxBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Elements", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Elements = append(m.Elements, &OutgoingTransferTx{})
			if err := m.Elements[len(m.Elements)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TotalFee == nil {
				m.TotalFee = &ERC20Token{}
			}
			if err := m.TotalFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgedDenominator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BridgedDenominator == nil {
				m.BridgedDenominator = &BridgedDenominator{}
			}
			if err := m.BridgedDenominator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchStatus", wireType)
			}
			m.BatchStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchStatus |= BatchStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Valset == nil {
				m.Valset = &Valset{}
			}
			if err := m.Valset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenContract", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenContract = append(m.TokenContract[:0], dAtA[iNdEx:postIndex]...)
			if m.TokenContract == nil {
				m.TokenContract = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OutgoingTransferTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OutgoingTransferTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OutgoingTransferTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestAddress = append(m.DestAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.DestAddress == nil {
				m.DestAddress = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Amount == nil {
				m.Amount = &ERC20Token{}
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBatch
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBatch
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BridgeFee == nil {
				m.BridgeFee = &ERC20Token{}
			}
			if err := m.BridgeFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBatch(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthBatch
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBatch(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBatch
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBatch
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBatch
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBatch
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBatch
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBatch        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBatch          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBatch = fmt.Errorf("proto: unexpected end of group")
)
