[workspace]
members = ["orchestrator", "cosmos_gravity", "ethereum_gravity", "gravity_utils", "proto_build", "test_runner", "gravity_proto", "relayer", "gbt"]
default-members = ["gbt"]


[patch.crates-io]
deep_space = {git = "https://github.com/public-awesome/deep_space", branch="fix/query-for-tx"}

